### ISSUE TITLE
FurnaceSmeltEvent console spam

### ISSUE THREAD

**Issue by AeSix** [TheBusyBiscuit/Slimefun4#862] opened 2019-03-27 17:49 UTC
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.

This has been going on for several builds.  It seems the items are being processed properly, but I'm not 100% positive on that.  

## Server Log
All Error files/messages need to be provided via http://pastebin.com/

(I found termbin to be easier to use, apologies if this is a henderence)
https://termbin.com/wdsh

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

see below, first occurrence of issue is in code block.

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

I'm using Paper build 588, CS-CoreLib #36, SlimeFun #77, ChestTerminal #3, ExoticGarden #7 and Luckyblocks #3.   I'm uncertain if this is a CS-CoreLib, SlimeFun, or ChestTerminal issue. 

```
[13:40:41] [Server thread/ERROR]: Could not pass event FurnaceSmeltEvent to Slimefun vDEV - 77 (git 02ee0f1c)
java.lang.NullPointerException: null
        at me.mrCookieSlime.Slimefun.listeners.FurnaceListener.onSmelt(FurnaceListener.java:42) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor439.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-588]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-588]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-588]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.TileEntityFurnace.burn(TileEntityFurnace.java:367) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.TileEntityFurnace.tick(TileEntityFurnace.java:314) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1427) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1100) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-588]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-588]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by TheBusyBiscuit** [comment] 2019-03-27 17:54
Duplicate of #856

**Closed by TheBusyBiscuit** 2019-03-27 17:54 UTC
