### ISSUE TITLE
Item Registration failed: APPLE_PIE

### ISSUE THREAD

**Issue by AaronHzy** [TheBusyBiscuit/Slimefun4#626] opened 2018-03-05 13:03 UTC
## Description
Error at startup

## Server Log
`[20:59:41 WARN]: [Slimefun] Item Registration failed: APPLE_PIE
[20:59:41 WARN]: java.lang.IllegalArgumentException: ID "APPLE_PIE" already exists
[20:59:41 WARN]:        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.register(SlimefunItem.java:224)
[20:59:41 WARN]:        at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup.setupItems(SlimefunSetup.java:3055)
[20:59:41 WARN]:        at me.mrCookieSlime.Slimefun.SlimefunStartup.onEnable(SlimefunStartup.java:169)
[20:59:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:59:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[20:59:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:59:41 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[20:59:41 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[20:59:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[20:59:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[20:59:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[20:59:41 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[20:59:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[20:59:41 WARN]:        at java.lang.Thread.run(Unknown Source)`

## Environment
CS-CoreLib-1.5.16
Slimefun-4.1.13
PaperSpigot-1.12.2-b1327

**Comment by Redemption198** [comment] 2018-03-05 14:16
Duplicate of #559.

**Closed** 2018-03-05 20:18 UTC
