### ISSUE TITLE
could not pass event BlockBreakEvent 

### ISSUE THREAD

**Issue by kiritss** [TheBusyBiscuit/Slimefun4#436] opened 2017-09-13 22:57 UTC
## Description
Error printed on console for blockbreakevent

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/KbFwLgST

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://pastebin.com/KbFwLgST

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

latest sf (4.1.10)
CS-CoreLib v1.5.15
Latest version of Paperspigot for version 1.11.2

**Comment by Poslovitch** [comment] 2017-12-01 21:33
Duplicate of #367, #287 and #255

**Closed** 2017-12-01 22:07 UTC
