### ISSUE TITLE
GPS Teleporter Pylon disappears

### ISSUE THREAD

**Issue by Fluffy-7** [TheBusyBiscuit/Slimefun4#1105] opened 2019-09-08 22:42 UTC
## Description (Required)
When the user put the block, it disappears.

## Steps to reproduce the Issue (Required)
 [https://imgur.com/CRe6IjU](url)

## Expected behavior (Required)
Put the block and complete the GPS teleporter.

## Server Log / Error Report
https://pastebin.com/raw/QmGUsZdi

## Environment (Required)
[https://imgur.com/ifbV7r5](url)

**Comment by TheBusyBiscuit** [comment] 2019-09-08 22:43
Duplicate of #1098

**Comment by TheBusyBiscuit** [comment] 2019-09-08 22:43
Also, learn to use links. Your links are always empty because you enter the URL as the name, not the link...

**Closed by TheBusyBiscuit** 2019-09-08 22:43 UTC
Labels: Bug Report
