### ISSUE TITLE
java.lang.IllegalArgumentException: ID "HOT_CHOCOLATE" already exists

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#575] opened 2018-01-12 17:32 UTC
## Description
You've successfully fixed Hot Chocolate in the Christmas recipes, yay!  But... it's the same name as an existing item from Exoit Garden so... oops.

## Server Log
On every startup:
```
[22:51:18] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden v1.6.3
[22:51:18] [Server thread/WARN]: [Slimefun] Item Registration failed: HOT_CHOCOLATE
[22:51:18] [Server thread/WARN]: java.lang.IllegalArgumentException: ID "HOT_CHOCOLATE" already exists
[22:51:18] [Server thread/WARN]: 	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.register(SlimefunItem.java:224)
[22:51:18] [Server thread/WARN]: 	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.register(SlimefunItem.java:218)
[22:51:18] [Server thread/WARN]: 	at me.mrCookieSlime.ExoticGarden.ExoticGarden.registerDishes(ExoticGarden.java:545)
[22:51:18] [Server thread/WARN]: 	at me.mrCookieSlime.ExoticGarden.ExoticGarden.onEnable(ExoticGarden.java:112)
[22:51:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:51:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:51:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:51:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[22:51:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[22:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[22:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[22:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[22:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[22:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[22:51:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```
## Evidence / Proof
See above

## Environment
CraftBukkit v1_12_R1 (latest)
CS-CoreLib v1.5.16
Slimefun v4.1.13 (dev 4-17)

**Comment by Poslovitch** [comment] 2018-01-12 19:54
Duplicate of #559

**Comment by TheBusyBiscuit** [comment] 2018-01-13 09:13
@Poslovitch It is not.

**Comment by Poslovitch** [comment] 2018-01-13 11:40
It's the same problem that is explained in the issue above.
However, yes, it's not, cause the error comes from Exotic Garden : 

```
[22:51:18] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden v1.6.3
[22:51:18] [Server thread/WARN]: [Slimefun] Item Registration failed: HOT_CHOCOLATE
```

**Comment by TheBusyBiscuit** [comment] 2018-01-13 11:58
@Poslovitch 
Just the same exception, but needs a different approach.
Also, christmas items have some festively colored item names I think, so the ItemStacks differ in both cases.
Otherwise I would have suggested an inline if-else for the season difference and a .setCategory call for ExoticGarden.

**Comment by MrKiller01** [comment] 2018-02-03 11:25
Ah well, it came in the dark and I hope it leaves that way too....

[12:12:28 WARN]: [Slimefun] Item Registration failed: HOT_CHOCOLATE
[12:12:28 WARN]: java.lang.IllegalArgumentException: ID "HOT_CHOCOLATE" already
exists
[12:12:28 WARN]:        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.Slimef
unItem.register(SlimefunItem.java:224)
[12:12:28 WARN]:        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.Slimef
unItem.register(SlimefunItem.java:218)
[12:12:28 WARN]:        at me.mrCookieSlime.ExoticGarden.ExoticGarden.registerDi
shes(ExoticGarden.java:545)
[12:12:28 WARN]:        at me.mrCookieSlime.ExoticGarden.ExoticGarden.onEnable(E
xoticGarden.java:112)
[12:12:28 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug
in.java:264)
[12:12:28 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(
JavaPluginLoader.java:337)
[12:12:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si
mplePluginManager.java:403)
[12:12:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlu
gin(CraftServer.java:381)
[12:12:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlu
gins(CraftServer.java:330)
[12:12:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(Minec
raftServer.java:422)
[12:12:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(Minec
raftServer.java:383)
[12:12:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(Minec
raftServer.java:338)
[12:12:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(De
dicatedServer.java:272)
[12:12:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min
ecraftServer.java:545)
[12:12:28 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:12:28 INFO]: [CraftBook] Enabling CraftBook v3.9-SNAPSHOT-jenkins-CraftBook-
194
[12:12:28 INFO]: [CraftBook] Loading persistent data from YAML!

**Comment by Pythonic-Rainbow** [comment] 2018-02-20 16:45
Whoops I am sorry @TheBusyBiscuit XD I overlooked this issue

**Closed** 2018-02-20 22:47 UTC
