### ISSUE TITLE
Ancient Altars and Pedistals are now named vanilla blocks

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1019] opened 2019-08-20 12:33 UTC
## Description (Required)
Items no longer function as an "Ancient Altar".  Have tried re-crafting and replacing several even using the /sf give command, they no longer work as intended.

## Steps to reproduce the Issue (Required)
https://imgur.com/a/spVNMbG

## Expected behavior (Required)
Should operate as an ancient altar for crafting items.

## Server Log / Error Report
Nothing appears in logs in regards to this.  I believe the first few builds of slimefun still had an operational altar as I think some people used theirs when I first reopened as 1.14.  However since build #135 or so, this has stopped working.

## Environment (Required)
[08:32:27 INFO]: Paper v1_14_R1 (173)
[08:32:27 INFO]:
[08:32:27 INFO]: CS-CoreLib vDEV - 66 (git 9174f09d)
[08:32:27 INFO]: Slimefun vDEV - 142 (git 0d7fc6af)
[08:32:27 INFO]:
[08:32:27 INFO]: Installed Addons (7)
[08:32:27 INFO]:  Barrels vDEV - 2 (git 847bc83b)
[08:32:27 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[08:32:27 INFO]:  ChestTerminal v1.0
[08:32:27 INFO]:  HotbarPets vDEV - 10 (git 7d790905)
[08:32:27 INFO]:  ExoticGarden vDEV - 17 (git 122f5555)
[08:32:27 INFO]:  SoulJars vDEV - 3 (git ebabf39f)
[08:32:27 INFO]:  ElectricSpawners vDEV - 2 (git 49ffa319)

**Comment by TheBusyBiscuit** [comment] 2019-08-20 14:43
I'd probably say this is also a duplicate of #1020 
To me it looks like the data serialization is bugged.
The build you describe also marks the time where data storage changed from simple-json to gson.

**Closed by TheBusyBiscuit** 2019-08-20 14:43 UTC
Labels: Bug Report

**Comment by mrcoffee1026** [comment] 2019-08-20 14:56
ah i'd have expected these two to be unrelated, but alrighty then.  If that's true there are likely other affected blocks as well, but for now this is the only thing I've found so far, other items are working.
