### ISSUE TITLE
Juices do not restore hunger/saturation

### ISSUE THREAD

**Issue by coldcode69** [TheBusyBiscuit/Slimefun4#87] opened 2017-01-05 00:16 UTC
## Description
None of the juices (Carrot Juice, Melon Juice, etc) restore any hunger or saturation when using spigot 1.11.2.

## Evidence / Proof
Checked using a clean server.
![hunger](https://cloud.githubusercontent.com/assets/24900603/21663799/5de1378a-d2da-11e6-92cc-7147c5ed43c2.gif)

I also checked the NBT data in the player file to see if the hidden saturation value changed at all.

Before:
![nbt1](https://cloud.githubusercontent.com/assets/24900603/21663808/6ea94544-d2da-11e6-8a20-7ca2ed4e2278.png)
After consuming all juices:
![nbt2](https://cloud.githubusercontent.com/assets/24900603/21663810/700c3a0e-d2da-11e6-9f95-28cdadabeb3d.png)

## Environment
spigot 1.11.2
cscorelib version 1.5.12
slimefun version 4.1.1

**Comment by NathanAdhitya** [comment] 2017-01-08 12:03
Anything on console?

**Comment by SoSeDiK** [comment] 2017-01-10 10:52
Same problem (also with ExoticGarden). I just added the command /effect [player] 23 [time] [level] (/effect [player] 23 3 1 for juice, for example), when the potion is consumed. Maybe there is a better way.

**Comment by Momshroom** [comment] 2017-03-29 04:49
Sorry, how did you do that? :3

**Comment by CyberiumShadow** [comment] 2017-04-06 07:08
`	@EventHandler
	public void onStarve(FoodLevelChangeEvent e) {
		if (e.getFoodLevel() < ((Player) e.getEntity()).getFoodLevel()) {
			Player p = (Player) e.getEntity();
			for (ItemStack item: p.getInventory().getContents()) {
				if (SlimefunManager.isItemSimiliar(item, SlimefunItem.getItem("COOLER"), false)) {
					Inventory inv = Backpacks.getInventory(p, item);
					if (inv != null) {
						ItemStack drink = null;
						for (ItemStack i: inv.getContents()) {
							if (i != null && i.getType() == Material.POTION && i.hasItemMeta()) {
								drink = i;
								break;
							}
						}
						if (drink != null) {
							PotionMeta im = (PotionMeta) drink.getItemMeta();
							for (PotionEffect effect: im.getCustomEffects()) {
								p.addPotionEffect(effect);
							}
							p.setSaturation(6F);
							p.playSound(p.getLocation(), Sound.ENTITY_GENERIC_DRINK, 1F, 1F);
							inv.removeItem(drink);
							Backpacks.saveBackpack(inv, item);
							break;
						}
					}
				}
			}
		}
	}`

That's the listener code.

Essentially, there is no hook for slimefun to add the saturation effect when you drink a juice individually.

The juices will only work when put into a cooler.

*however*
This will reset your hunger bar to full as soon as you lose even a single food point as I tested with the elemental staff wind.

@TheBusyBiscuit I'm not sure if that was intended behaviour nor am I sure if this is intended behaviour of consuming 2 juices per "restoration"

**Comment by TheBusyBiscuit** [comment] 2017-04-06 08:03
@CyberiumShadow 
> Essentially, there is no hook for slimefun to add the saturation effect when you drink a juice individually.
There is no need for that either since Juices are Potions and the Potion Effect is applied by Minecraft itself.
At least, that is what Spigot is supposed to do.

**Comment by CyberiumShadow** [comment] 2017-04-06 09:55
Yeah I had a look through the source for Slimefun and The javadocs for Spigot. 

I have a feeling its more a spigot issue. 

However, could it be changed so that instead of consuming a juice on every foodlevel change.

have it consume it if the new food level is under a certain threshold

**Comment by TheBusyBiscuit** [comment] 2017-04-06 13:53
@CyberiumShadow It's Open-Source.

**Comment by Poslovitch** [comment] 2017-11-25 21:58
Duplicate of #333

**Comment by Poslovitch** [comment] 2017-12-01 17:07
Has to be closed too (https://github.com/TheBusyBiscuit/Slimefun4/pull/513)

**Closed** 2017-12-01 17:09 UTC
