### ISSUE TITLE
Disenchanter Duplication bug

### ISSUE THREAD

**Issue by MsArtix** [TheBusyBiscuit/Slimefun4#532] opened 2017-12-12 05:17 UTC
## Description
Dupe bug with disenchanter. You need SF and the a crates plugin or I guess most any other plugin that allows for enchanted items that are not normally enchanted like slimeball/magma cream or a hook.
Steps to reproduce bug:
1. Have slimefun and enchanted item other than normal MC items like an enchanted Hook or enchanted slimeball/magma cream. 
2. Place book and 2 or more enchanted hook into disenchanter. 
3. Wait for it to finish. 
4. It gives you 2 of the input item such as the enchanted hook, and you still have one left to disenchant. Now for me, it still let me use the disenchanted hook to unlock a crate. IE the enchanted hook was used as a key for crates on my server. So it uses one of the enchanted item. Then it gives you back the stack size on the left side. So if you used 2 items, it would return 2 items plus the item that wasnt disenchanted yet. aka you now have 3 items that can be used for crates or whatever you put in there. 

## Server Log
Server log is completely irrelevant. 

## Environment
craftbukkit 1.12_R1
CS-Corelib v1.5.16
SF V 4.1.12

**Comment by Poslovitch** [comment] 2017-12-12 05:25
This bug cannot be fixed by Slimefun, and therefore must be handled by the crate plugin.
Please contact its owner.

**Comment by TheBusyBiscuit** [comment] 2017-12-12 12:53
Please include visual evidence...

**Comment by MsArtix** [comment] 2017-12-12 19:01
The pictures are out of order but none the less they show it. The duped keys still work when opening a crate and the other guys of course still work. I also can do this with other items. I tested it on enchanted snowballs and enchanted magacream. The snowballs/magamcream are from another plugin I use that just gives the item a glow effect (they dont actually have enchants on them).

**Comment by mrcoffee1026** [comment] 2017-12-13 20:19
Confirmed, and the duplicated and disenchanted keys as well as the original all function.  This is a bug I've noticed before but hadn't given a thought since the items it provided extras of are typically worthless:  you can disenchant stacks of grandma's/grandpa's walking sticks and end up with many more named sticks than you started with.  The disenchanter simply cannot be relied upon to count the stacks properly for whatever reason, please look into this since it can be used for bad things (like crate keys).

**Comment by mrcoffee1026** [comment] 2018-04-27 00:07
This merge should have closed this ticket:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#20

**Comment by VoidAngel** [comment] 2018-04-27 01:16
Yup this ticket and #580

**Closed** 2018-04-27 10:53 UTC
