### ISSUE TITLE
Automated Crafting Chamber not crafting sf recipes 

### ISSUE THREAD

**Issue by Acegaming1011** [TheBusyBiscuit/Slimefun4#901] opened 2019-04-26 08:57 UTC
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
I'm using the automated crafting chambers and for some reason I can't get the tiny piles of uranium to craft into small chunks and then into actually uranium
## Server Log
All Error files/messages need to be provided via http://pastebin.com/

## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
![2019-04-26_04 53 45](https://user-images.githubusercontent.com/44754404/56795915-7e8c4280-67df-11e9-96b6-5091e338ac33.png)

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
https://cdn.discordapp.com/attachments/398426813363388416/571256520726151168/unknown.png

**Comment by Pajlis** [comment] 2019-04-28 01:36
This is the same as #822

**Comment by Acegaming1011** [comment] 2019-04-28 01:38
Is there an expected time to when it’s gonna get fixed?

**Comment by TheBusyBiscuit** [comment] 2019-04-28 22:06
Duplicate of #822

**Closed by TheBusyBiscuit** 2019-04-28 22:06 UTC
