### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [TheBusyBiscuit/Slimefun4#592] opened 2018-02-09 19:01 UTC
timings
https://timings.aikar.co/?id=177f5d7af02a4293af8be01f221cf231#plugins

logs
https://gist.github.com/KonoromiHimaries/f8c8426ec5b3af8e19c4707780f22475

only some error

**Comment by Redemption198** [comment] 2018-02-09 21:06
Duplicate of https://github.com/TheBusyBiscuit/Slimefun4/issues/559. Next time please use the issue template and set an appropriate title (https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/ISSUE_TEMPLATE.md).

**Closed** 2018-02-09 21:16 UTC
