### ISSUE TITLE
Monstery Jerky removes wrong item when consumed

### ISSUE THREAD

**Issue by coldcode69** [TheBusyBiscuit/Slimefun4#89] opened 2017-01-05 10:59 UTC
## Description
When Monstery Jerky is held in the left hand, it deletes the item held in the right hand. The Monster Jerky is never removed, no matter how many times you consume it. It looks like slimefun is trying to delete the jerky after you eat it but wrongly assumes it is always in the right hand. I tested Beef Jerky and it doesn't have the same problem.

## Evidence / Proof
![monsterjerky](https://cloud.githubusercontent.com/assets/24900603/21678047/f9cf236e-d334-11e6-9d4e-aff5d4d1b141.gif)

## Environment
spigot 1.11.2
cscorelib version 1.5.12
slimefun version 4.1.1

**Comment by NathanAdhitya** [comment] 2017-01-05 12:40
Confirmed, It happens, It only happens on the Monster Jerky since the Beef Jerky just enhances the saturation given, instead of having to cancel the eating event too.

For sure, this is a CS-CoreLib Bug, One fix that may help is that to use the way that the old juice bug was fixed. (And that is to check the item first, before removing, and prioritizing offhand.)

**Comment by NathanAdhitya** [comment] 2017-01-10 10:57
I think this should be marked as closed and fixed? yet?

**Closed** 2017-01-10 14:55 UTC
Labels: Bug Report
