### ISSUE TITLE
can you add worldedit support?

### ISSUE THREAD

**Issue by rybuilder23** [TheBusyBiscuit/Slimefun4#813] opened 2018-12-06 12:32 UTC
## Description (Required)
slimefun lets worldedit crash

can you add worldedit    

## Server Log
https://pastebin.com/LZj1iBiQ

## Environment (Required)
Minecraft1.13.2 
CS-CoreLib-29.jar
Slimefun4-58.jar

latest worldedit beta 3

**Comment by PrzemoVi** [comment] 2018-12-07 21:51
Fixed in my pull request: https://github.com/TheBusyBiscuit/Slimefun4/pull/814

My modified .jars (both cscorelib and slimefun):
https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5

Mods:
Fixed worldedit 7 (request https://github.com/TheBusyBiscuit/Slimefun4/pull/814)
Fixed enchanted furnaces (https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64)
Fixed auto. crafting. table, electric furnace and charging bench (https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64)

**Comment by axemwa** [comment] 2018-12-09 08:41
> 
> 
> Use my modified .jars (both cscorelib and slimefun):
> https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5
> 
> Fixed worldedit 7 (my request #814)
> Fixed enchanted furnaces and lumber axe duplication glitch (#810)
> Fixed auto. crafting. table, electric furnace and charging bench (my request [TheBusyBiscuit/CS-CoreLib#64](https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64))
> 
> Warn: This will broke support with worldedit older than 7.0!!!

Thanx I was also having this issue, will you be moving these modified jar(s) to development builds?

**Comment by PrzemoVi** [comment] 2018-12-09 19:42
I created a pull request here: https://github.com/TheBusyBiscuit/Slimefun4/pull/814#issuecomment-445560705
Hope, it will get merged :)

**Comment by MothGirlMusic** [comment] 2018-12-11 15:21
does your .jars fix the italics issue of https://github.com/TheBusyBiscuit/Slimefun4/issues/803#issuecomment-446210254 ?

**Comment by PrzemoVi** [comment] 2018-12-11 17:31
> 
> 
> does your .jars fix the italics issue of [#803 (comment)](https://github.com/TheBusyBiscuit/Slimefun4/issues/803#issuecomment-446210254) ?

Not, but I can fix this

**Comment by PrzemoVi** [comment] 2018-12-11 17:47
Done. I fixed it ;)

Use my modified .jars (both cscorelib and slimefun):
https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5

Fixed worldedit 7 (my request https://github.com/TheBusyBiscuit/Slimefun4/pull/814)
Fixed enchanted furnaces and lumber axe duplication glitch (https://github.com/TheBusyBiscuit/Slimefun4/pull/810)
Fixed auto. crafting. table, electric furnace and charging bench (my request https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64)
Fixed Ancient Altar itemstack fixing ;)

Warn: This will broke support with worldedit older than 7.0!!!

**Comment by axemwa** [comment] 2018-12-18 17:48
> 
> 
> Done. I fixed it ;)
> 
> Use my modified .jars (both cscorelib and slimefun):
> https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5
> 
> Fixed worldedit 7 (my request #814)
> Fixed enchanted furnaces and lumber axe duplication glitch (#810)
> Fixed auto. crafting. table, electric furnace and charging bench (my request [TheBusyBiscuit/CS-CoreLib#64](https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64))
> Fixed Ancient Altar itemstack fixing ;) (my request #814)
> 
> Warn: This will broke support with worldedit older than 7.0!!!

"/slimefun guide" doesn't seem to work in this version, I'm using 1.13.2

**Comment by PrzemoVi** [comment] 2018-12-18 18:12
Everything is working on my and my friend's servers.
Try updating spigot to the latest build.

**Comment by MothGirlMusic** [comment] 2018-12-18 19:11
its working perfectly on my 1.13.2 servers too! [except sensibletoolbox]

**Comment by MothGirlMusic** [comment] 2018-12-18 20:21
i've done that but none of the commands show up and in the slimefun guide also nothing shows up.. did you update it since adding it?

**Comment by axemwa** [comment] 2018-12-18 21:59
> 
> 
> Everything is working on my and my friend's servers.
> Try updating spigot to the latest build.

I using paper would that be affecting it?

**Comment by MothGirlMusic** [comment] 2018-12-18 23:55
it'd be a really good guess as to why.. a lot of plugins don't support paper because of its weird handling on worldgen and other stuff.

**Comment by axemwa** [comment] 2018-12-19 02:52
> 
> 
> it'd be a really good guess as to why.. a lot of plugins don't support paper because of its weird handling on worldgen and other stuff.

True but even though a lot of plugins don't support paper... most plugins do. Paper has much better performace and the devs fix bugs a lot quicker, I used to use spigot but had too many performance issues due to the amount of plugins I run and/or test, however paper can handle it just fine so that's one of the reasons I choose it. 

Also most devs don't have a problem updating for compatibility with paper it's like comparing minecraft 1.8 to 1.13.2 obviously the newer/more updated it is the better and if ppl miss 1.8 mechanics they can just use a plugin that handles that in 1.13.2 anyway so it's a win win. 

Paper still has everything that spigot does but like a computers CPU it has been overclocked/tweaked up so that it runs at better performace and in turn yes it may affect how it handles some things, but with some minor tweaking in a plugins code by the dev(s), those problems/incompatibilities can be easily dealt with in most cases and I always make sure to thank them if they do have to manually add in compatibility with paper, luckily in my case when I made my 1st spigot plugin it was already compatible with paper.

Ps: Sorry for babbling on anyway sometimes I get way to specific about things.

**Comment by axemwa** [comment] 2018-12-19 02:52
Anyway back on topic, @PrzemoVi I will test this on a fresh/new spigot server and fresh paper servermyself to see if paper incompatibility is the issue here and will let you know how I go take care all

**Comment by MothGirlMusic** [comment] 2018-12-19 04:40
all i can say is it works on spigot. haven't had much luck with paper.

**Comment by axemwa** [comment] 2018-12-19 06:16
yeah same the plugin works in paper just fine... minus the /slimefun guide command...
anyway @rybuilder23 if the issue is fixed you can [close] the issue now

**Comment by axemwa** [comment] 2018-12-19 06:49
@PrzemoVi @MothGirlMusic Sorry guys I made a mistake, turns out it does work in paper cause I assumed the guide came up in chat but it's in a book and didn't realize my bad haha not a paper issue after all :D

**Comment by axemwa** [comment] 2018-12-19 06:51
This plugin is so cool

**Comment by PrzemoVi** [comment] 2018-12-19 06:55
@MothGirlMusic
Go to SensibleToolbox config and change textures to:

texture:
    input: cyan_stained_glass_pane
    output: orange_stained_glass_pane
    bg: blue_stained_glass_pane
    label: book
    button: oak_button

Now it should work. I will upload version with fixed config tomorrow

Have fun!

**Closed** 2018-12-29 20:03 UTC
Labels: Fixed/Added
