### ISSUE TITLE
Cannot break android blocks

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1021] opened 2019-08-20 13:08 UTC
## Description (Required)
Once placed, android blocks are permanently stuck where they are until someone with worldedit is able to remove them.

## Steps to reproduce the Issue (Required)
Place any android.  Try to break it so you can place it somewhere else.
https://youtu.be/gVinZ4rjqss

## Expected behavior (Required)
I saw a note in the past about requiring a tool for slimefun blocks but have also tried breaking one with a tool which also did not work.  Probably doesn't matter but neither does creative mode and the debug fish.

## Server Log / Error Report
No errors.

## Environment (Required)
[09:08:14 INFO]: Paper v1_14_R1 (173)
[09:08:14 INFO]:
[09:08:14 INFO]: CS-CoreLib vDEV - 66 (git 9174f09d)
[09:08:14 INFO]: Slimefun vDEV - 142 (git 0d7fc6af)
[09:08:14 INFO]:
[09:08:14 INFO]: Installed Addons (7)
[09:08:14 INFO]:  Barrels vDEV - 2 (git 847bc83b)
[09:08:14 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[09:08:14 INFO]:  ChestTerminal v1.0
[09:08:14 INFO]:  HotbarPets vDEV - 10 (git 7d790905)
[09:08:14 INFO]:  ExoticGarden vDEV - 17 (git 122f5555)
[09:08:14 INFO]:  SoulJars vDEV - 3 (git ebabf39f)
[09:08:14 INFO]:  ElectricSpawners vDEV - 2 (git 49ffa319)

**Comment by TheBusyBiscuit** [comment] 2019-08-20 14:39
Duplicate of #997

**Closed by TheBusyBiscuit** 2019-08-20 14:39 UTC
Labels: Bug Report

**Comment by mrcoffee1026** [comment] 2019-08-20 17:36
oops sorry didn't see that.
