### ISSUE TITLE
Using Enhanced Furnace - Console Spam

### ISSUE THREAD

**Issue by Josh19992016** [TheBusyBiscuit/Slimefun4#856] opened 2019-03-24 15:49 UTC
## Description (Required)
As soon as an Enhanced Furnace V is used, item put into it, an error is spammed in the console, server seems to be running fine while in game, worried the Enhanced Furnace could cause issues.

## Server Log
https://pastebin.com/eghp5zjH 

## Evidence / Proof (Required)
There is no error provided in game, and furnace operates as it should.

## Environment (Required)
Spigot 1.13.2 Server
CS-CoreLib- vDEV - 35 (git 30d7c341)
Slimefun vDEV - 68 (git 89a8b6b5)

**Comment by AeSix** [comment] 2019-03-27 18:02
I didn't realize I created a duplicate of this issue. My apologies.  I am using newer versions than what listed here, however.  As well as a different server.  Hopefully that data will be of use. :)

**Comment by SoSeDiK** [comment] 2019-03-27 19:00
@Josh19992016, @AeSix
Can you show us your plugins list?
Mostly I'm interesned in plugins which change/add/remove furnace recipes.

**Comment by Josh19992016** [comment] 2019-03-27 19:11
Here are my plugins:

Plugins (10): CoreProtect, LuckPerms, CS-CoreLib, Slimefun, Vault, ConsoleSpamFix, DiscordSRV, Essentials, EssentialsSpawn, EssentialsChat

It has to be related to Slimefun however as its a Slimefun item causing the log

**Comment by SoSeDiK** [comment] 2019-03-27 19:16
I set up many working furnaces but still don't get a NPE.
To understand the logics:
1. Smelt event is fired. Therefore, Minecraft knows exactly that this recipe exists.
2. Plugin goes through every registere furnace recipe that Minecraft knows to get the proper result.
3. If it is not another plugin causing that the existing recipe has no result then I don't know. I made a null check just in case.

**Comment by SoSeDiK** [comment] 2019-03-27 19:18
Oh, I forget about data packs. Do you have any of them?
I don't know if they can cause this though.

**Comment by Josh19992016** [comment] 2019-03-27 19:19
I don't no, but don't know much about the how the plugin works, I just use it :/

**Comment by SoSeDiK** [comment] 2019-03-27 19:28
It shouldn't throw or cause any issues after the next update but I'm still confused about the reason of this.

**Comment by AeSix** [comment] 2019-03-27 20:10
```
AngryWolves, Arconix*, Barrels, BuycraftX*, CatChat*, ChestTerminal, CommandBook, CommandHelper, Craftconomy3*, CS-CoreLib, Custom-Hat*, DuckTrails*, EasySetSpawn*, EchoPet*, EditableSign*, ExoticGarden, FastAsyncWorldEdit*, FirstJoinPlus*, FrostWalkerDefense*, GriefPrevention, Guilds*, HolographicDisplays, InfernalMobs, InfoBook*, LibsDisguises, LockettePro, LogBlock, LogBlockQuestioner*, MineResetLite*, MineResetLitePlus*, ModReq*, MultiHome*, OnTime*, OpenInv*, PermissionsEx*, PlaceholderAPI, PrimeTokens, PriorityLogin*, ProtocolLib*, PurpleIRC*, QuickShop, RainbowArmour*, RedstoneClockDetector*, RepairPlus*, ScheduledAnnouncer2*, Shopkeepers, SignURLs*, SimpleVoteListener*, Slimefun, SlimefunLuckyBlocks, STFU*, StopPushing*, Titles*, TokenRewards*, VanishNoPacket, Vault*, Votifier*, WarpPortals*, Wild*, WorldBorder, WorldEdit, WorldGuard
```

Nothing that should be interfering.  Maybe Barrels (also a Slimefun addon)? 

Sorry for the delay.

**Closed** 2019-03-27 20:21 UTC
