### ISSUE TITLE
Exception caught while ticking a Block:java.lang.NumberFormatException

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#363] opened 2017-07-23 21:05 UTC
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Exception caught while ticking a Block:java.lang.NumberFormatException

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

```
Server Software: Paper
  Build: git-Paper-1147 (MC: 1.12)
  Minecraft: 1.12-R0.1-SNAPSHOT

Installed Plugins (69)
  + Vehicles 8.6
  + PlugMan 2.1.3
  + PlayerWarp [v1.1 release]
  + BetterChairs 0.9.4
  + NametagEdit 4.1.7
  + MineMarket-Universal 2.94
  + UltimateVotes 1.6.7
  + EntityDetection 1.0 (build #12)
  + DisablePistonFarming 0.3
  + Stats 1.0.0
  + icJukeBox 1.6.4
  + CoreProtect 2.14.2
  + AnvilRestrict 0.1
  + MineMarketAPI 1.0
  + OpenInv 3.2.1
  + CreativeNbtControl 1.8
  + XrayInformer 3.5.0
  + AutoMessage 2.5.5
  + NoSpawnerChange 1.6
  + Heads 1.9.8
  + WorldBorder 1.8.7
  + Votifier 2.3.5
  + ProtocolLib 4.3.0
  + OpenTerrainGenerator 1.10.2 v18
  + FastAsyncWorldEdit 17.07.12-6b6f285-750-13.7.8
  + RedstoneClockDetector 0.2.7-b12
  + PermissionsEx 1.23.4
  + Lottery 1.1.1
  + mcMMO 1.5.08-SNAPSHOT
  + CS-CoreLib 1.5.16
  + Vault 1.6.1
  + FastAsyncVoxelSniper 17.07.12-6b6f285-750-13.7.8
  + AuctionHouse 3.3
  + VoxelSniper 5.171.0-SNAPSHOT
  + MyCommand 5.3.4
  + WorldEdit 6.1.7;dd00bb1
  + Essentials 2.0.1-b498
  + CompatNoCheatPlus 6.6.4-RC-sMD5NET-b88
  + SafeTrade 1.0.15
  + NoCheatPlus 3.15.2-SNAPSHOT-sMD5NET-b1113
  + EssentialsChat 2.0.1-b498
  + PartyChatSpy 1.2
  + ShareControl 2.6.4
  + PlotSquared 3.5.1-SNAPSHOT-3633576
  + WorldGuard 6.2.2-SNAPSHOT;1708-3a8e3e8
  + Slimefun 4.1.9
  + LockettePro 2.8.1
  + myZone 1.1.170
  + EssentialsGeoIP 2.0.1-b498
  + RandomTeleport 1.7.4 (build #20)
  + PvPManager 3.7.5
  + EssentialsSpawn 2.0.1-b498
  + TitleManager 2.0.7
  + ExtraGear 1.1.1
  + Multiverse-Core 2.5.0-b727
  + Shopkeepers 1.82
  + SlimefunLuckyBlocks 1.1
  + ExoticGarden 1.6.3
  + CraftBook 3.9-SNAPSHOT-jenkins-CraftBook-158
  + ChestShop 3.8.13-SNAPSHOT (build #26)
  + ElectricSpawners 1.0
  + MobArena 0.98.1
  + SkinsRestorer 13.1.2
  + Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714
  + LimitedCreative 2.3-SNAPSHOT-256f165622
  + MyPet 2.3.5
  + AreaShop 2.4.0
  + ChatControl 7.4.11

Ticked Block:
  World: world
  X: 7762
  Y: 65
  Z: 4979

Slimefun Data:
  ID: CARGO_MANAGER
  Inventory: false
  Data: {"id":"CARGO_MANAGER","visualizer":"disabled"}

Stacktrace:

java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.getFrequency(CargoNet.java:465)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:528)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:486)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:479)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:505)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:486)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.tick(CargoNet.java:96)
	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$125.tick(SlimefunSetup.java:5110)
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

```

Server Software: Paper
  Build: git-Paper-1147 (MC: 1.12)
  Minecraft: 1.12-R0.1-SNAPSHOT

Installed Plugins (69)
  + Vehicles 8.6
  + PlugMan 2.1.3
  + PlayerWarp [v1.1 release]
  + BetterChairs 0.9.4
  + NametagEdit 4.1.7
  + MineMarket-Universal 2.94
  + UltimateVotes 1.6.7
  + EntityDetection 1.0 (build #12)
  + DisablePistonFarming 0.3
  + Stats 1.0.0
  + icJukeBox 1.6.4
  + CoreProtect 2.14.2
  + AnvilRestrict 0.1
  + MineMarketAPI 1.0
  + OpenInv 3.2.1
  + CreativeNbtControl 1.8
  + XrayInformer 3.5.0
  + AutoMessage 2.5.5
  + NoSpawnerChange 1.6
  + Heads 1.9.8
  + WorldBorder 1.8.7
  + Votifier 2.3.5
  + ProtocolLib 4.3.0
  + OpenTerrainGenerator 1.10.2 v18
  + FastAsyncWorldEdit 17.07.12-6b6f285-750-13.7.8
  + RedstoneClockDetector 0.2.7-b12
  + PermissionsEx 1.23.4
  + Lottery 1.1.1
  + mcMMO 1.5.08-SNAPSHOT
  + CS-CoreLib 1.5.16
  + Vault 1.6.1
  + FastAsyncVoxelSniper 17.07.12-6b6f285-750-13.7.8
  + AuctionHouse 3.3
  + VoxelSniper 5.171.0-SNAPSHOT
  + MyCommand 5.3.4
  + WorldEdit 6.1.7;dd00bb1
  + Essentials 2.0.1-b498
  + CompatNoCheatPlus 6.6.4-RC-sMD5NET-b88
  + SafeTrade 1.0.15
  + NoCheatPlus 3.15.2-SNAPSHOT-sMD5NET-b1113
  + EssentialsChat 2.0.1-b498
  + PartyChatSpy 1.2
  + ShareControl 2.6.4
  + PlotSquared 3.5.1-SNAPSHOT-3633576
  + WorldGuard 6.2.2-SNAPSHOT;1708-3a8e3e8
  + Slimefun 4.1.9
  + LockettePro 2.8.1
  + myZone 1.1.170
  + EssentialsGeoIP 2.0.1-b498
  + RandomTeleport 1.7.4 (build #20)
  + PvPManager 3.7.5
  + EssentialsSpawn 2.0.1-b498
  + TitleManager 2.0.7
  + ExtraGear 1.1.1
  + Multiverse-Core 2.5.0-b727
  + Shopkeepers 1.82
  + SlimefunLuckyBlocks 1.1
  + ExoticGarden 1.6.3
  + CraftBook 3.9-SNAPSHOT-jenkins-CraftBook-158
  + ChestShop 3.8.13-SNAPSHOT (build #26)
  + ElectricSpawners 1.0
  + MobArena 0.98.1
  + SkinsRestorer 13.1.2
  + Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714
  + LimitedCreative 2.3-SNAPSHOT-256f165622
  + MyPet 2.3.5
  + AreaShop 2.4.0
  + ChatControl 7.4.11

Ticked Block:
  World: plotworld
  X: -367
  Y: 58
  Z: 2244

Slimefun Data:
  ID: CARGO_MANAGER
  Inventory: false
  Data: {"id":"CARGO_MANAGER"}

Stacktrace:

java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.getFrequency(CargoNet.java:465)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:528)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:486)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:505)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:505)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:505)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:479)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.continueScan(CargoNet.java:521)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.scan(CargoNet.java:505)
	at me.mrCookieSlime.Slimefun.api.item_transport.CargoNet.tick(CargoNet.java:96)
	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$125.tick(SlimefunSetup.java:5110)
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
Installed Addons (4)
ExtraGear v1.1.1
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
ElectricSpawners v1.0
```

**Comment by Poslovitch** [comment] 2017-08-10 14:14
Duplicate of https://github.com/TheBusyBiscuit/Slimefun4/issues/161

**Comment by Poslovitch** [comment] 2017-08-10 14:31
Just ran through the code and saw the frequency of a Cargo Manager is never set.
However, the Cargo Manager does not have a frequency.

I'm investigating to see where #getFrequency(Location) is called for a CargoManager.

**Comment by TheBusyBiscuit** [comment] 2017-08-11 16:28
@Poslovitch It is not weird. Cargo Managers call the Cargo Net, simple as that.

**Closed** 2017-08-11 16:30 UTC
Labels: Bug Report
