### ISSUE TITLE
MultipleIssues

### ISSUE THREAD

**Issue by MsArtix** [TheBusyBiscuit/Slimefun4#520] opened 2017-12-02 02:56 UTC
## Description
2 issues, First is a big error log when people use the AutoSmelt Pickaxe, second is when people use MCMMO treefeller ability on a fruit tree **sometimes** the fruit glitches out and you cannot place blocks where the fruit was. This can be fixed by selecting the area with world edit and setting it to air. 

## Server Log
Note: this only contains the errors, my full server log around enormous and not needed. This is for the smelting pickaxe not working right, I tested it on redstone ore and it gave the first error then it came again on gold ore. 
https://hastebin.com/hebajebepi.vbs

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
CraftBukkit 1.12.1 (using spigot actually) but /sf versions says craftbukkit
SF version 4.1.10
CoreLib V 1.5.16
Exotic Garden 1.6.3

**Comment by Poslovitch** [comment] 2017-12-02 07:29
Please create one issue per bug/error.

The Smelter's Pickaxe bug is a duplicate of #367, which will be fixed soon (I started working on it yesterday)

The second bug comes from ExoticGarden and should therefore be reported at it's bug tracker.

**Closed** 2018-03-05 20:19 UTC
