### ISSUE TITLE
Data error with the "energy-charge"

### ISSUE THREAD

**Issue by EterLzb** [TheBusyBiscuit/Slimefun4#1123] opened 2019-09-13 14:37 UTC
## Description (Required)
Data error with the "energy-charge" about Capacitance,
it will create a null.sfb in /data-storage/Slimefun/stored-blocks.
## Steps to reproduce the Issue (Required)
Place a capacitor next to the power core, remove the capacitor, place the capacitor again, and then restart the server.
You will see the warn like the following "Server Log / Error Report"
## Expected behavior (Required)
Capacitance "energy-charge" data should be recorded correctly.
## Server Log / Error Report
```
[21:12:40 WARN]: [Slimefun] Corrupted file detected!
[21:12:40 WARN]: [Slimefun] Slimefun will simply skip this File, but you
[21:12:40 WARN]: [Slimefun] should maybe look into it!
[21:12:40 WARN]: [Slimefun] data-storage/Slimefun/stored-blocks/world/null.sfb
```
Contents of "null.sfb"
```
world;1275;63;-687: '{"energy-charge":"0"}'
world;1273;63;-687: '{"energy-charge":"0"}'
world;1274;63;-688: '{"energy-charge":"0"}'
world;1275;63;-689: '{"energy-charge":"0"}'
world;1274;63;-687: '{"energy-charge":"0"}'
world;1275;63;-688: '{"energy-charge":"0"}'
world;1271;63;-688: '{"energy-charge":"0"}'
...
```
## Environment (Required)
 - Minecraft Version: 1.14.4
 - Slimefun Version: Slimefun4 - DEV 252 (git 25ee0)
 - CS-CoreLib Version: CS-CoreLib - DEV 76 (git aaef2)

**Comment by TheBusyBiscuit** [comment] 2019-09-13 14:40
Thanks for posting this with all information now.

But again, it is just a warning that you can ignore.
It's not a bug, nor an error. Just a warning, nothing that can nor should be fixed.

Try to pay attention to the channel of these messages.
If it says INFO or WARN, then you can ignore it. Only errors need to be fixed.

**Closed by TheBusyBiscuit** 2019-09-13 14:40 UTC
Labels: Bug Report
