### ISSUE TITLE
Exp Bug for all Furnaces

### ISSUE THREAD

**Issue by zThundy** [TheBusyBiscuit/Slimefun4#920] opened 2019-05-29 22:32 UTC
## Description (Required)
When i want to put inside a furnace just coal using cargo input and outputs, it appear to be sorted in all the inventory. See video for more details

## Steps to reproduce the Issue (Required)
https://youtu.be/WV-vpA0eFL8

## Expected behavior (Required)
To just see coal in the fuel slot

## Server Log / Error Report
No error, just this problem.

## Environment (Required)

 - Minecraft Version: 1.9.4
 - Slimefun Version: Slimefun4 - #52
 - CS-CoreLib Version: CS-CoreLib vDEV - 33

**Comment by TheBusyBiscuit** [comment] 2019-06-11 11:09
Duplicate of #114

**Closed by TheBusyBiscuit** 2019-06-11 11:09 UTC
Labels: Bug Report
