### ISSUE TITLE
Nuclear reactor access port eats Uranium

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#1205] opened 2019-10-25 02:06 UTC
## Description (Required)
Uranium works as a fuel in a Nuclear reactor as normal if input directly into the Nuclear reactor, but if you place it into the detected Nuclear access port, it empties the supply one at a time until empty and produces no power from it.  (coolant cells sent to the access port deliver to the reactor just fine)

## Steps to reproduce the Issue (Required)
Set up access port and attempt to fuel with Uranium/Boosted Uranium from the access port.

## Expected behavior (Required)
Should consume the fuel source and provide around 20 minutes of operation.  Instead fuel is consumed but no operation takes place.

## Server Log / Error Report
No log activity.

## Environment (Required)
[22:06:02 INFO]: Paper v1_14_R1 (221)
[22:06:02 INFO]:
[22:06:02 INFO]: CS-CoreLib vDEV - 78 (git 199e1b1e)
[22:06:02 INFO]: Slimefun vDEV - 323 (git 57e11265)
[22:06:02 INFO]:
[22:06:02 INFO]: Installed Addons (13)
[22:06:02 INFO]:  Barrels vDEV - 7 (git 0d14dd9f)
[22:06:02 INFO]:  SlimeXpansion vDEV - 4 (git 5bf10c29)
[22:06:02 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[22:06:02 INFO]:  ChestTerminal vDEV - 17 (git 933a7d36)
[22:06:02 INFO]:  EmeraldEnchants vDEV - 5 (git 6adbbb87)
[22:06:02 INFO]:  HotbarPets vDEV - 20 (git cd87bc60)
[22:06:02 INFO]:  ExoticGarden vDEV - 22 (git a855f5b7)
[22:06:02 INFO]:  SoulJars vDEV - 4 (git 4a600aa2)
[22:06:02 INFO]:  SlimefunOreChunks vDEV - 2 (git 24d90a3e)
[22:06:02 INFO]:  ElectricSpawners vDEV - 5 (git c3f8cc9d)
[22:06:02 INFO]:  ExtraHeads v1.1
[22:06:02 INFO]:  PrivateStorage vDEV - 6 (git b012877e)
[22:06:02 INFO]:  DyedBackpacks vDEV - 1 (git 4b4d1f0f)

**Comment by TheBusyBiscuit** [comment] 2019-10-25 05:01
Duplicate of #893

**Closed** 2019-10-25 05:01 UTC
Labels: Bug Report
