### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by pinkpig3777** [TheBusyBiscuit/Slimefun4#287] opened 2017-05-13 16:01 UTC
**## Description
Describe your Issue AS DETAILED AS POSSIBLE.**
I got this console error, how can it be fixed?
https://pastebin.com/Y6CPtvkT

**## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.**
https://pastebin.com/nx2YeUrd

**## Evidence / Proof**
It's a console issue. I'm not sure what proof to provide because I can't understand what the error means. Hence why I'm reporting it. 

**## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.**
Spigot 1.10
CS-CoreLib 1.5.14
SlimeFun 4.1.8

Thank you.

**Comment by teamaonn** [comment] 2017-05-13 17:55
Oh i know this one! It's world guard! Right? What do I win?

**Comment by pinkpig3777** [comment] 2017-05-15 18:19
Huh. I got an email of your reply asking if it was worldguard but I don't see the reply on here.. As for asking about worldguard, I have worldguard but I'm not sure what the issue is because it mentioned Slimefun.

**Comment by Poslovitch** [comment] 2017-08-12 13:12
Duplicate of https://github.com/TheBusyBiscuit/Slimefun4/issues/367

**Closed** 2017-12-01 22:07 UTC
Labels: Bug Report
