### ISSUE TITLE
Carbonado Edged Furnace either behaves vanilla or duplicates items

### ISSUE THREAD

**Issue by FatherWh0** [TheBusyBiscuit/Slimefun4#411] opened 2017-08-27 23:06 UTC
## Description
Most of the time the carbonado edged furnace behaves as a vanilla furnace. On rare occasion, when one is loaded with ores and fuel, the furnace gui closes. Then the furnace begins to generate drops of the ore and fuel it has been loaded with. Attempting to reopen the gui to remove items results in the gui closing itself again. The furnace must be broken (mined) to stop the production of drops. In the images provided the drops are being generated by the furnace.

## Server Log
There are no unusual log entries or errors that occur.
https://gist.github.com/FatherWh0/c7300ff46ab1d45ded589cbdc65a8af3

## Evidence / Proof
https://prnt.sc/gds8pg
http://imgur.com/fI1JBNo

## Environment
Server: paper 1.12.1 R0.1 # 1195
Slimefun v4.1.10
CS-CoreLib v.1.5.16
SlimefunGuidPlus v1.0
ExoticGarden v1.6.3
SlimefunLuckyBlocks v1.1

**Comment by andris155** [comment] 2017-08-29 12:25
same problem

**Comment by 100petr** [comment] 2017-09-02 16:33
It also makes me...

**Comment by galacticwarrior9** [comment] 2017-09-10 09:31
Also having this. Very serious issue.

**Comment by 100petr** [comment] 2017-09-10 09:33
almost 2 weeks and still unpatched.

**Comment by mrcoffee1026** [comment] 2017-09-10 20:07
Seems to preserve the fuel efficiency but runs same speed as vanilla oven.

**Comment by Goldenphelix** [comment] 2017-09-11 02:13
Issue present in Slimefun 4.1.10, serious issue for my server, please fix this asap!!
Plugins:
Slimefun v4.1.10
CS-CoreLib v.1.5.16
ExoticGarden v1.6.3
SlimefunLuckyBlocks v1.1

**Comment by mrcoffee1026** [comment] 2017-09-12 00:06
Confirmed item duplication.. although it also appears to be duplicating whatever is present in the fuel slot also (went to smelt pair of gold boots... oven began exploding out drops of boots and wood planks... it only took me a moment to mine the thing, but by then I had 10 golden boots and 10 stacks of wood planks to collect along with the oven itself).  Same versions listed less the Luckyblocks.

**Comment by fonkfader** [comment] 2017-09-16 14:45
same issue...

**Comment by Stoniasawsome** [comment] 2017-09-22 18:48
same issue

**Comment by FatherWh0** [comment] 2017-10-13 17:47
The problem has now spread to the Enhanced Furnace XI.

**Comment by 100petr** [comment] 2017-10-13 19:17
Author is probably ignoring the problem -_-

**Comment by TheBusyBiscuit** [comment] 2017-10-13 19:19
@100petr 
I retired ~1.5 years ago, so of course I am...

**Comment by Poslovitch** [comment] 2017-10-14 08:33
And it's very hard to figure out where the problem comes from : the code hasn't change since the release of SF4, and it broke on 1.11 - 1.12. I've already made a few unsuccessful troubleshoots. I even opened an issue on Spigot's bug tracker - they said the problem should not come from them.

In facts, I have been watching this repo for months, and it always gave me an unpleasant feeling when I saw people saying "wtf is this shit, this dosnt work anymor". TheBusyBiscuit is retired from plugin dev, this is written in BIG RED CAPITALS on the bukkit plugin's page and Slimefun is maintained by collaborators that want to spend some spare time on it. TheBusyBiscuit now only does the upkeep : merging pull requests, closing invalid issues, publishing new releases.

Anyway, time for me to go back working on some features.

**Comment by Goldenphelix** [comment] 2017-10-14 08:54
But this could be the final downfall of slimefun. It's one of the best vanilla>modded plugins ever made. It's one of the biggest features of my server  (currently 3000 unique players joined in the last 2 months and a daily peak of 20-30)and it's a real shame if this doesn't get fixed.. I love this plugin along with so many other people @TheBusyBiscuit. I would hate to see it become broken and forgotten like so many other good plugins I've seen die in the recent years.. hopefully someone with a heart will help fix this issue..

**Comment by John000708** [comment] 2017-10-14 10:32
@Goldenphelix why so melodramatic... It's simply an issue. Worst case scenario DISABLE the furnaces and don't bother with them again. After all, they aren't such a big part of Slimefun. I'll try to fix the issue so I stop getting spammed with emails from this thread.

**Comment by Goldenphelix** [comment] 2017-10-14 10:39
Ouch! I was just trying to make a point dude. Chill. Good luck to you. They are popular on my survival server. Thus why I'm here.

**Comment by FatherWh0** [comment] 2017-10-15 02:20
@TheBusyBiscuit (formerly mrCookieSlime) Thank you for an awesome plugin that brought a whole new dimension to Minecraft. Sometimes things you are doing get old and it's time to move on. Just know we appreciate all you've done.
@John000708 Thank you for all you've been doing. We've noticed to fixed issues, the upgrades, even new items added in the last 1.5 years. Know that your time and effort is greatly appreciated. Indeed you are correct. It is simple enough to disable a dysfunctional item and not lose sleep over it. Slimefun has so much depth one or two disabled items isn't going to do any great harm. 
To all previously involved and currently involved thank you for giving our servers a new level of depth and fun for the thousands of players who have enjoyed and continue to enjoy this terrific plugin. I take my hat off to you and your grand efforts for us, the server owners some of whom know how to show appreciation and some of whom not so much.

**Comment by Diinl** [comment] 2017-10-15 22:43
Just alittle comment... Furnace listener may need updating since the way furnace events worked changed in 1.12.1

**Comment by ScuroK** [comment] 2017-10-17 22:20
why dont you guys put slimefun on spigot? Bukkitdev is so buggy and old. If u put it on spigot it will bring more life to it.

**Comment by Fisherman-wcz** [comment] 2017-10-22 05:21
same issue

**Comment by Paxelcfg** [comment] 2017-10-26 12:58
Hello. https://youtu.be/vveIdyuV4uA Video of the bug

**Comment by 100petr** [comment] 2017-12-16 21:14
The problem persists.

**Comment by John000708** [comment] 2018-01-10 19:41
@FatherWh0 @Goldenphelix would you mind giving me a list with all of your installed plugins? Trying to narrow down the issue to specific plugins. Protection plugins could be the problem.

**Comment by FatherWh0** [comment] 2018-01-11 18:39
It appears you've fixed all the furnaces in v4.1.13. I've tested enhanced, electric and carbonado edged and all appear to be working normally again.
Thank you.

**Comment by mrcoffee1026** [comment] 2018-01-12 18:12
They work fine till I restart my server, at that point the duplication (and mess making) exists with every furnace (not electrics, those were never affected to my knowledge) that was placed in world at the last server shut down.  All of those need to be broken and placed again in order to stop the problem from recurring in each of them... a fix which lasts until the next server restart, at which point all furnaces must be broken and placed again.

**Comment by FatherWh0** [comment] 2018-01-12 23:23
@mrcoffee1026 Which version of Slimefun and Spigot are you currently running?

**Comment by mrcoffee1026** [comment] 2018-01-13 02:57
@FatherWh0 
CraftBukkit v1_12_R1 (latest build as of 1/12/18)
Slimefun v4.1.13 (dev version 4-17)

**Comment by mrcoffee1026** [comment] 2018-01-16 20:32
After some residual restarts, a couple of other unrelated plugin updates, this seemed to stop happening and I haven't had to replace an oven for awhile, I'm not sure what the deal was.

**Comment by FatherWh0** [comment] 2018-03-16 23:53
It appears this problem has returned with carbonado edged furnaces with slimefun v4.1.14.
paper 1.12.2 build 1349.
If I roll back to slimefun v4.1.13 the problem goes away.

**Comment by mrcoffee1026** [comment] 2018-03-17 01:07
I assure you it's been consistently there since like 4.1.1, it's just really inconsistent about when it shows up.  They've cleared up the speed issue more recently but the part where they vomit drops everywhere is a long-standing issue, not one that is related to this last release which made no changes to the furnaces that I'm aware of.

**Closed** 2019-08-25 08:58 UTC
